name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, "lts/*"]

    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: web
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: "cat .env.test >> $GITHUB_ENV"
      - run: NODE_ENV=test yarn test
